version: '3'

services:
  django:
    build: .
    volumes:
      - .:/code
      - static-volume:/static
    expose:
      - 8000

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static-volume:/static
    ports:
      - "80:80"
    depends_on:
      - django

volumes:
  static-volume: