version: '3'

services:
  db:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dokupe
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: ocelot
      MYSQL_PASSWORD: dokupe
  django:
    build: .
    volumes:
      - .:/code
      - static-volume:/static
    expose:
      - 8000
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/nginx:/var/log/nginx
      - static-volume:/static
    ports:
      - "80:80"
      - 443:443
    depends_on:
      - django
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

volumes:
  static-volume: