# Generated by Django 3.1.7 on 2023-07-26 07:08

import app1.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterVoiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_voice', models.CharField(max_length=256)),
                ('yomigana', models.CharField(blank=True, max_length=256, null=True)),
                ('cv_id', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name_plural': 'character voice lists',
            },
        ),
        migrations.CreateModel(
            name='CircleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle', models.CharField(max_length=256)),
                ('yomigana', models.CharField(blank=True, max_length=256, null=True)),
                ('circle_id', models.CharField(blank=True, max_length=16, null=True)),
                ('url_circle', models.CharField(blank=True, max_length=127, null=True)),
                ('publication_state', models.CharField(blank=True, max_length=16, null=True)),
                ('approval_state', models.CharField(blank=True, max_length=16, null=True)),
                ('supplement', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Circle lists',
            },
        ),
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=64)),
                ('yomigana', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Genre lists',
                'ordering': ['yomigana'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioWriterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_writer', models.CharField(blank=True, max_length=256, null=True)),
                ('yomigana', models.CharField(blank=True, max_length=256, null=True)),
                ('sw_id', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name_plural': 'Scenario Writer lists',
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default='None', max_length=100)),
                ('ip_address', models.CharField(default='0.0.0', max_length=50)),
                ('user', models.CharField(default='None', max_length=30)),
                ('elapsed_time', models.FloatField(default=0)),
                ('adddate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_record_id', models.CharField(default=app1.models.create_public_record_id, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('work_id', models.CharField(max_length=31)),
                ('release_date', models.DateField()),
                ('add_date', models.DateField(default=datetime.datetime.now)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('url_af', models.CharField(blank=True, max_length=255)),
                ('url_img', models.CharField(blank=True, max_length=255)),
                ('commerce_switch', models.BooleanField(default=True)),
                ('public_switch', models.BooleanField(default=True)),
                ('public_delete', models.BooleanField(default=False)),
                ('sample_switch', models.BooleanField(default=True)),
                ('adult_switch', models.BooleanField(default=True)),
                ('confidence', models.FloatField(default=100)),
                ('display_range', models.IntegerField(default=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_original', models.TextField(blank=True, null=True)),
                ('description_conv', models.TextField(blank=True, null=True)),
                ('chapter_names', models.CharField(blank=True, max_length=4096, null=True)),
                ('maintext_original', models.TextField(blank=True, null=True)),
                ('maintext', models.TextField()),
                ('maintext_conv', models.TextField(blank=True, null=True)),
                ('maintext_old', models.TextField(blank=True, null=True)),
                ('text_version', models.CharField(blank=True, max_length=64, null=True)),
                ('character_voice', models.ManyToManyField(blank=True, to='app1.CharacterVoiceModel')),
                ('circle', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='app1.circlemodel')),
                ('genres', models.ManyToManyField(blank=True, to='app1.GenreModel')),
                ('scenario_writers', models.ManyToManyField(blank=True, related_name='scenario_writers_many', to='app1.ScenarioWriterModel')),
            ],
            options={
                'verbose_name_plural': 'Voice Data lists',
            },
        ),
    ]
