# Generated by Django 3.1.7 on 2023-08-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicedatamodel',
            name='uid',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
